### ISSUE TITLE
type error at wiki?

### ISSUE THREAD

**Issue by l1t1** [CuriosAI/sai#21]
https://github.com/sai-dev/sai/wiki/Client-server-communication
Under Linux and macOS, you must be sure that `leelaz` executable location is included in the PATH environment variable, or that it is in the same directory from where you are launching autogtp.

leelaz should be sai>

**Comment by Vandertic** [comment]
Yes, thank you

**Comment by amato-gianluca** [comment]
Fixed.

**Comment by l1t1** [comment]
this page still exists error
https://github.com/sai-dev/sai/wiki/Installation

**Comment by amato-gianluca** [comment]
Ooops... you are right!

I fixed the installation page, and checked the others for the same typo. Hope it is fine now.
